### ISSUE TITLE
CSS dependency observed.

### ISSUE THREAD

**Issue by sohaibjaved44** [alexanderar/Mvc.CascadeDropDown#5] opened 2016-04-09 07:40 UTC
HI Dear, 
I have used this cascadeDropDown and it works fine but I'm facing one problem. I have checked that if I put @class="selectpicker" rather than "form-control" it do not render data in cascadedDropdown. 
I can not use form-control ... 
I have seen in inspect element, values are there but are not showing up just because of this class selectpicker. However with razor dropdownlistfor it works with this css class perfect.

**Comment by alexanderar** [comment] 2016-04-10 07:15
Hello Sohaib,
I reviewed the issue. The issue is actually not a `CascadeDropDown` issue but it is a general issue with dynamically changing a content of select input when using `bootstrap-select` (check [this thread](http://stackoverflow.com/questions/23514318/bootstrap-select-reinitialize-on-dynamically-added-element)). This behavior could be easily fixed by refreshing the `selectpicker` content each time that  selected value changes. So this code should do the trick (since `bootstrap-select` has a dependency on jQuery, the following code uses it as well):

```
<script>
    $(function() {
        $(".selectpicker").on("change", function() {
            $(this).selectpicker('refresh');
        });
    });  
</script>`
```

**Closed as completed by alexanderar** 2016-04-10 07:15 UTC
Labels: help wanted

**Comment by sohaibjaved44** [comment] 2016-05-05 02:58
Ok Great, Thanks I am enjoying this cascaded dropdown.
